# 条件判断与错误处理

## 一、fail模块

- 在执行playbook时，如果playbook中的任何一个任务执行失败，playbook都会停止运行，除非这个任务设置了`ignore_errors: true`，在任务没有设置`ignore_errors: true`的情况下，任务执行失败后，playbook就会自动终止，而fail模块天生就是一个用来"执行失败"的模块，当fail模块执行后，playbook就会认为有任务失败，从而终止运行

### 1、下列playbook中一共有4个debug任务，在第2个debug任务之后，调用了fail模块，
```
- hosts: web
  remote_user: root
  tasks:
  - debug:
      msg: "1"
  - debug:
      msg: "2"
  - fail:
  - debug:
      msg: "3"
  - debug:
      msg: "4"
```

```
# ansible-playbook test.yml 

PLAY [node] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
Sunday 26 September 2021  10:22:52 -0400 (0:00:00.104)       0:00:00.104 ****** 
ok: [node01]

TASK [debug] *******************************************************************************************************************************************
Sunday 26 September 2021  10:22:53 -0400 (0:00:00.871)       0:00:00.976 ****** 
ok: [node01] => {
    "msg": "1"
}

TASK [debug] *******************************************************************************************************************************************
Sunday 26 September 2021  10:22:53 -0400 (0:00:00.079)       0:00:01.060 ****** 
ok: [node01] => {
    "msg": "2"
}

TASK [fail] ********************************************************************************************************************************************
Sunday 26 September 2021  10:22:53 -0400 (0:00:00.073)       0:00:01.134 ****** 
fatal: [node01]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}
	to retry, use: --limit @/root/test.retry

PLAY RECAP *********************************************************************************************************************************************
node01                     : ok=3    changed=0    unreachable=0    failed=1   

Sunday 26 September 2021  10:22:53 -0400 (0:00:00.050)       0:00:01.185 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------- 0.88s
debug ------------------------------------------------------------------------------------------------------------------------------------------- 0.08s
debug ------------------------------------------------------------------------------------------------------------------------------------------- 0.07s
fail -------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
```

### 2、fail模块默认的输出信息为`Failed as requested from task`，可以通过fail模块的msg参数自定义报错的信息
```
---
- hosts: web
  remote_user: root
  tasks:
  - debug:
      msg: "1"
  - fail:
      msg: "Interrupt running playbook"
  - debug:
      msg: "2"
```

```
# ansible-playbook test.yml 

PLAY [node] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
Sunday 26 September 2021  10:22:12 -0400 (0:00:00.058)       0:00:00.058 ****** 
ok: [node01]

TASK [debug] *******************************************************************************************************************************************
Sunday 26 September 2021  10:22:13 -0400 (0:00:00.921)       0:00:00.979 ****** 
ok: [node01] => {
    "msg": "1"
}

TASK [fail] ********************************************************************************************************************************************
Sunday 26 September 2021  10:22:13 -0400 (0:00:00.097)       0:00:01.077 ****** 
fatal: [node01]: FAILED! => {"changed": false, "msg": "Interrupt running playbook"}
	to retry, use: --limit @/root/test.retry

PLAY RECAP *********************************************************************************************************************************************
node01                     : ok=2    changed=0    unreachable=0    failed=1   

Sunday 26 September 2021  10:22:13 -0400 (0:00:00.056)       0:00:01.134 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------- 0.92s
debug ------------------------------------------------------------------------------------------------------------------------------------------- 0.10s
fail -------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
```

### 3、`fail`模块通常需要对某些条件进行判断，如果条件满足，则中断剧本，所以，fail模块通常与when结合使用,比如如果之前模块执行后的标准输出信息中包含字符串’error’，则认为中断剧本的条件成立，就立即调用fail模块，以终断playbook
```
---
- hosts: web
  remote_user: root
  tasks:
  - shell: "echo 'This is a string for testing--error'"
    register: return_value
  - fail:
      msg: "Conditions established,Interrupt running playbook"
    when: "'error' in return_value.stdout"
  - debug:
      msg: "I never execute,Because the playbook has stopped"
```

使用in或者not in条件判断时正确写法
```
when: ' "successful" not in return_value.stdout '
when: " 'successful' not in return_value.stdout "
```

```
# ansible-playbook test.yml 

PLAY [node] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
Sunday 26 September 2021  10:20:55 -0400 (0:00:00.088)       0:00:00.088 ****** 
ok: [node01]

TASK [shell] *******************************************************************************************************************************************
Sunday 26 September 2021  10:20:57 -0400 (0:00:01.301)       0:00:01.389 ****** 
changed: [node01]

TASK [fail] ********************************************************************************************************************************************
Sunday 26 September 2021  10:20:57 -0400 (0:00:00.475)       0:00:01.864 ****** 
fatal: [node01]: FAILED! => {"changed": false, "msg": "Conditions established,Interrupt running playbook"}
	to retry, use: --limit @/root/test.retry

PLAY RECAP *********************************************************************************************************************************************
node01                     : ok=2    changed=1    unreachable=0    failed=1   

Sunday 26 September 2021  10:20:57 -0400 (0:00:00.057)       0:00:01.922 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------- 1.30s
shell ------------------------------------------------------------------------------------------------------------------------------------------- 0.48s
fail -------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
```


## 二、failed_when模块

### 1、借助`failed_when`功能实现失败判断，`failed_when`的作用就是，当对应的条件成立时，将对应任务的执行状态设置为失败
```
---
- hosts: web
  remote_user: root
  tasks:
  - debug:
      msg: "I execute normally"
  - shell: "echo 'This is a string for testing error'"
    register: return_value
    failed_when: ' "error" in return_value.stdout'
  - debug:
      msg: "I never execute,Because the playbook has stopped"
```

```
# ansible-playbook test.yml 

PLAY [node] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
Sunday 26 September 2021  10:13:27 -0400 (0:00:00.093)       0:00:00.093 ****** 
ok: [node01]

TASK [debug] *******************************************************************************************************************************************
Sunday 26 September 2021  10:13:27 -0400 (0:00:00.788)       0:00:00.881 ****** 
ok: [node01] => {
    "msg": "I execute normally"
}

TASK [shell] *******************************************************************************************************************************************
Sunday 26 September 2021  10:13:27 -0400 (0:00:00.067)       0:00:00.949 ****** 
fatal: [node01]: FAILED! => {"changed": true, "cmd": "echo 'This is a string for testing error'", "delta": "0:00:00.002876", "end": "2021-09-26 10:13:28.316925", "failed_when_result": true, "rc": 0, "start": "2021-09-26 10:13:28.314049", "stderr": "", "stderr_lines": [], "stdout": "This is a string for testing error", "stdout_lines": ["This is a string for testing error"]}
	to retry, use: --limit @/root/test.retry

PLAY RECAP *********************************************************************************************************************************************
node01                     : ok=2    changed=0    unreachable=0    failed=1   

Sunday 26 September 2021  10:13:28 -0400 (0:00:00.377)       0:00:01.327 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------- 0.79s
shell ------------------------------------------------------------------------------------------------------------------------------------------- 0.38s
debug ------------------------------------------------------------------------------------------------------------------------------------------- 0.07s
```

## 三、changed_when模块

### 1、`changed_when`模块的作用是在条件成立时，将对应任务的执行状态设置为changed
```
---
- hosts: web
  remote_user: root
  tasks:
  - debug:
      msg: "test message"
    changed_when: 2 > 1
```

```
# ansible-playbook test.yml 

PLAY [node] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
Sunday 26 September 2021  10:24:46 -0400 (0:00:00.071)       0:00:00.071 ****** 
ok: [node01]

TASK [debug] *******************************************************************************************************************************************
Sunday 26 September 2021  10:24:47 -0400 (0:00:00.953)       0:00:01.024 ****** 
changed: [node01] => {
    "msg": "test message"
}

PLAY RECAP *********************************************************************************************************************************************
node01                     : ok=2    changed=1    unreachable=0    failed=0   

Sunday 26 September 2021  10:24:47 -0400 (0:00:00.051)       0:00:01.076 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------- 0.95s
debug ------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
```

###  2、将任务设置成永远不为changed状态
```
---
- hosts: test70
  remote_user: root
  tasks:
  - shell: "ls /opt"
    changed_when: false
```

```
# ansible-playbook test.yml 
 [WARNING]: While constructing a mapping from /root/test.yml, line 2, column 3, found a duplicate dict key (tasks). Using last defined value only.


PLAY [node] ********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
Sunday 26 September 2021  10:26:23 -0400 (0:00:00.055)       0:00:00.055 ****** 
ok: [node01]

TASK [shell] *******************************************************************************************************************************************
Sunday 26 September 2021  10:26:24 -0400 (0:00:00.903)       0:00:00.959 ****** 
ok: [node01]

PLAY RECAP *********************************************************************************************************************************************
node01                     : ok=2    changed=0    unreachable=0    failed=0   

Sunday 26 September 2021  10:26:24 -0400 (0:00:00.380)       0:00:01.341 ****** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------------- 0.90s
shell ------------------------------------------------------------------------------------------------------------------------------------------- 0.38s
```

### 3、changed_when简单使用
```
1.强制调用handlers
# cat test.yml 
- hosts: webserver
  force_handlers: yes                  #强制调用handlers
  tasks:
    - name: Touch File
      file: path=/tmp/bgx_handlers state=touch
      notify: Restart Httpd Server
    - name: Installed Packages
      yum: name=sb state=latest
  handlers:
    - name: Restart Httpd Server
      service: name=httpd state=restarted

2.关闭changed的状态(确定该tasks不会对被控端做任何的修改和变更.)
# cat test.yml 
- hosts: webserver
  tasks:
    - name: Installed Httpd Server
      yum: name=httpd state=present
    - name: Service Httpd Server
      service: name=httpd state=started
    - name: Check Httpd Server
      shell: ps aux|grep httpd
      register: check_httpd
      changed_when: false
    - name: OutPut Variables
      debug:
        msg: "{{ check_httpd.stdout_lines }}"


3、使用changed_when检查tasks任务返回的结果
# cat test.yml 
- hosts: webserver
  tasks: 
    - name: Installed Nginx Server
      yum: name=nginx state=present
    - name: Configure Nginx Server
      copy: src=./nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify: Restart Nginx Server
    - name: Check Nginx Configure Status
      command: /usr/sbin/nginx -t
      register: check_nginx
      changed_when: 
       - ( check_nginx.stdout.find('successful'))
       - false
    - name: Service Nginx Server
      service: name=nginx state=started 

  handlers:
    - name: Restart Nginx Server
      service: name=nginx state=restarted
```
